# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cloudflare-operator-system
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:FzUhkNnP1AgSPKF12W3pVMkVTmPIbaV8cAxCROh2hjZURK3l4eu2KA==,iv:XC6zCRQ/xp1QDKO1P5wyus5Sgi0a7MOEa5EGPke9qmI=,tag:5Y0w32hsRrusT/5z5n/dhw==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:ZugY2QwSnBjknh7HrQPj4zOPvvmlpmmVyuTEf+3uX9eY5f2fjg==,iv:5Q6TG5e6lBZyCHVR42UagSBG9v7RAkqqBEwOo5NYcrE=,tag:gKNRPsRl0Kj9k7hBEsuwLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17dcvp279ejrfxcjhtcj0cmvhkk3mxuz7jvyzqws250emwxy8v3mq2j4ye2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvV0NXME5LSlJaNTQ2eHRJ
            TEhoMEkzayswZE40cFovbG00SXZpSGV3WnlVCmJzUmVpb1JHMk1GK0cwWG5NVDU1
            dFpXWHZSNHVHZ0lLSndVRmgzMXN0OEUKLS0tIEE1NHRtaUY2dEkvZ2JLUTNkWmQ2
            T1pvUWxNZVBJZGViYU9BRGNQUzhBU0UK4euJ8+ToDs70dhRhsk9ov3JND8xlhFJB
            W/qtO1GuwtBIVIenu1vNmtM/dq0SNMxt3PlWq/qCyWaXNBtaxY7niQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-02T08:59:58Z"
    mac: ENC[AES256_GCM,data:NVd2qYz/XTxSeXwoup1j2ygSvf/PfkBxbu8nHZdTEAv5HQH70ENKfMX9tsKNtsYXY1wShyfufLmAjs/JM/cuhvhTXqQx5MMwwsTtrNUmqdKt2vJykR34o2RUd3HNfuQ46jFIrwG0dJBtbuyTlszzjvkjqFjWQ77mvsfZZ/QbF7M=,iv:WkK8Lfm+qei2m3Ww/J9f+mspeE+Gq4DvmeKI+hgvhYM=,tag:BXfPXK9lKAzi+/4pRikvDg==,type:str]
    pgp:
        - created_at: "2022-11-02T08:39:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D910MxD6sogoSAQdATnU6qpjXkqXbegdxpfA0cbfJ1/T3L6fdX+Dx7qKQyAow
            hlmZpWzSXuTBSFWOtD4KLNa7aW68FH1Pp/Iey8UST0Gnhpt7R9d5yWv4pwORR0II
            0lwBIs1kwILBx1NFt93etOjcBXcxTJiWZXXBkGZbCb00JWF2/S1DezIJmx3htPgk
            5xFmO7qkF8I6BQuBcBPwZCnY18dXI5oAiEgUVqsjkm+0aotUyrtW200lqGCESg==
            =VPC6
            -----END PGP MESSAGE-----
          fp: CDA57D7FFB3FD45FB56D179FCD40D20000800BDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
