---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: synology-csi-chart
  namespace: flux-system
spec:
  interval: 1h
  ref:
    # renovate: datasource=github-releases depName=christian-schlichtherle/synology-csi-chart
    tag: "v0.10.1"
  url: https://github.com/christian-schlichtherle/synology-csi-chart
