---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Asia/Shanghai"
  METALLB_LB_RANGE: 10.0.0.20-10.0.0.30
  METALLB_K8S_GATEWAY_ADDR: 10.0.0.20
  METALLB_INGRESS_ADDR: 10.0.0.21
  METALLB_CODER_ADDR: 10.0.0.22
