# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:7NMRPFe2Obtr,iv:qkdr+DoeqPYSMRHfM5Jcyd0rL0D9bSGGLfWb9YMtjCQ=,tag:fjzJ5ODGGTREw1BDEWU02g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OTI/tR7H4/IhvryGa374zdf2mA==,iv:q3VAxJxyB6yxZjKJOpJooClkDoEeI4lxaliKwMFxMR0=,tag:kR/d1YqkFI6merjYRrYgxg==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_NAME: ENC[AES256_GCM,data:9PXs8NLtjDs=,iv:O5v9liKOr1NUzVSSdtl+mG5UYGOsCZcM2HC9yjc8Isg=,tag:3VCDBZ/yWxJBfCqdU07/Sw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:3luYBt9XqE1mQMBm1r4kQjVhAg==,iv:1++q71J/x1q9A0w75AuIr4KLNI/PpY0Y57D2H54MgM8=,tag:Cb3mvuYPGtIGkpCBYs84uw==,type:str]
    SECRET_MASTODON_DOMAIN: ENC[AES256_GCM,data:ryGdYJWl64LE,iv:FIIbYr9dQq9/E1urSEqOKDmOkg+rHddpooVKb2Cxk3U=,tag:BowlOPdI1q73HQYCWdCFKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17dcvp279ejrfxcjhtcj0cmvhkk3mxuz7jvyzqws250emwxy8v3mq2j4ye2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMmRaOVlsS1VRVk50ZDJH
            U0E0NmFhMEtlNUd3alJZU3JtR21pbTRlUjFRClNhSm8wL3gzeVBMbU5kZXVGQlJP
            am9CVTVlejdGMU1jakdnUThVUTBvNzAKLS0tIGhjdEZGMWt3U0Ztc3M2ZU5ZVC9J
            SitybmllNXhrMGVXOHJGR0VSMTBwQmMKm1C7OBo8m5F90A+Z6/EjJKProOcJJlhg
            4YI9VbIycsPH09U8Qy/ZW/ugvcWL2mivKAV7Gx9nrNgsqE2COIc4eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-22T10:18:27Z"
    mac: ENC[AES256_GCM,data:FCNK9spskaJLlxjCknl2DNjSJ9bTkJsNhYd0sGOhhxiyZ8WlErbzvNJ0Lec+FNQco12ueFbgcKSNY5frZ0b6lBAb2JBEUZuM8woE+d3HjbAi0OdrgdXspSazxv3dWMDVNkmtYtEN5LclRtiauX8IelR1yPZ+SPtKBA5GDSjnNl4=,iv:XAB+DZIrUjrVBluyIxvMoG46tZ0+EMDMQ1vQjmHDnmU=,tag:coRPtAYtQ4a2Kd3N/B5xUA==,type:str]
    pgp:
        - created_at: "2022-11-01T10:08:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D910MxD6sogoSAQdA5HFBuZHdLTQjpdgSaUpc+LTC0jVsr0HClcrE5+q39wMw
            IIRo97rliPTYEbaPCW6B8pMpILxUdq+UcVZVzV3qzM8yyrpo74IpXoP9Y+wZstJ3
            0l4BmYkrIaxpJou9HW8K/vAgXyR7rEr0+fREZFaXdKw/ZzPiAYqq/tlD0HCAJWCK
            tMzplkao/Jp94VneBx+BGGMOocMAmhbd8Dhvydk0So/obj0KkxZyjyGbOT+IgMpq
            =sxiX
            -----END PGP MESSAGE-----
          fp: CDA57D7FFB3FD45FB56D179FCD40D20000800BDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
