---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-cleanup-operator
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-cleanup-operator
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: lwolf
        namespace: flux-system
      interval: 15m
  values:
    rbac:
      create: true
      global: true
    args:
      - --delete-successful-after=5m
      - --delete-failed-after=60m
      - --delete-pending-pods-after=0
      - --delete-evicted-pods-after=60m
      - --delete-orphaned-pods-after=60m
      - --legacy-mode=false
