---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: paperless
      version: 9.2.4
      sourceRef:
        kind: HelmRepository
        name: djjudas21
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    env:
      PAPERLESS_REDIS: redis://paperless-redis-master:6379
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: admin
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          auth.home.arpa/enabled: "true" # TODO: add auth
        hosts:
          - host: &host "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        size: 10Gi
      media:
        enabled: true
        size: 10Gi
      consume:
        enabled: true
        size: 10Gi
      export:
        enabled: true
        size: 10Gi
    redis:
      architecture: standalone
      enabled: true
