---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder-certificate
  namespace: coder
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager-issuers
      namespace: networking
  values:
    resources:
      - apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: "coder-${SECRET_DOMAIN/./-}"
          namespace: coder
        spec:
          secretName: "coder-${SECRET_DOMAIN/./-}-tls"
          issuerRef:
            name: letsencrypt-production
            kind: ClusterIssuer
          commonName: "coder.${SECRET_DOMAIN}"
          dnsNames:
            - "coder.${SECRET_DOMAIN}"
            - "*.coder.${SECRET_DOMAIN}"
