---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: gitea
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    gitea:
      admin:
        existingSecret: gitea-admin
      podAnnotations:
        secret.reloader.stakater.com/reload: gitea-admin
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: &host "gitea.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
