---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app descheduler
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: 0.25.2
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    kind: Deployment
    service:
      enabled: true
    serviceMonitor:
      enabled: false # Change after installing prometheus
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - *app
              topologyKey: kubernetes.io/hostname
