clusterName: home
talosVersion: v1.2.6
kubernetesVersion: v1.25.3
endpoint: https://10.0.0.10:6443
allowSchedulingOnControlPlanes: true

controlPlane:
  patches:
    - "@patch/disable-cni-and-proxy.yaml"
    - "@patch/extensions.yaml"
    - "@patch/kubelet-extra-mounts.yaml"
    # - "@patch/kubespan.yaml"
    - "@patch/remove-admission-control.yaml"
worker:
  patches:
    - "@patch/extensions.yaml"
    - "@patch/kubelet-extra-mounts.yaml"
    # - "@patch/kubespan.yaml"

nodes:
  - hostname: chopin
    ipAddress: 10.0.0.3
    controlPlane: true
    installDisk: /dev/nvme0n1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        addresses:
          - 10.0.0.3/24
        vip:
          ip: 10.0.0.10
    patches:
      - "@patch/kubelet-node-labels/home.yaml"

  - hostname: r86s
    ipAddress: 10.0.0.4
    controlPlane: true
    installDisk: /dev/mmcblk0
    networkInterfaces:
      - interface: eth0
        dhcp: true
        addresses:
          - 10.0.0.4/24
        vip:
          ip: 10.0.0.10
    patches:
      - "@patch/kubelet-node-labels/home.yaml"

  - hostname: delta
    ipAddress: 10.0.0.5
    controlPlane: true
    installDisk: /dev/nvme0n1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        addresses:
          - 10.0.0.5/24
        vip:
          ip: 10.0.0.10
    patches:
      - "@patch/kubelet-node-labels/home.yaml"
