clusterName: chopin
talosVersion: v1.2.6
kubernetesVersion: v1.25.3
endpoint: https://10.0.0.10:6443
allowSchedulingOnControlPlanes: true
nodes:
  - hostname: kmaster0
    ipAddress: 10.0.0.3
    controlPlane: true
    installDisk: /dev/nvme0n1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        addresses:
          - 10.0.0.3/24
        vip:
          ip: 10.0.0.10
controlPlane:
  patches:
    - "@patch/extensions.yaml"
    - "@patch/remove-admission-control.yaml"
worker:
  patches:
    - "@patch/extensions.yaml"
