---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: synology-csi-chart
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    clientInfoSecretName: synology-csi-secret
