---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cloudflare-operator
  namespace: cloudflare-operator-system
spec:
  interval: 10m
  path: ./config/default
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: cloudflare-operator
    namespace: flux-system
  patches:
    - target:
        kind: Deployment
        name: cloudflare-operator-controller-manager
        namespace: cloudflare-operator-system
      patch: |
        - op: add
          path: /spec/template/spec/containers/1/args/-
          value: --overwrite-unmanaged-dns=true
