kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: gitea-admin
    namespace: gitea
stringData:
    username: ENC[AES256_GCM,data:xq8Gyzo=,iv:P5bZoJrybcyRmf2BgNqDe78C4sLH6JODKmgUXljwBdM=,tag:l21sY0vMrERRu2l7d2Qm8g==,type:str]
    password: ENC[AES256_GCM,data:AZrAwYO0yQ==,iv:ZZHVSVro6yvksTr6kg6KU8xpypWQKr6VILXdouO66HU=,tag:RWFHmKFgvw374hurANz+6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17dcvp279ejrfxcjhtcj0cmvhkk3mxuz7jvyzqws250emwxy8v3mq2j4ye2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISEJOM1owZy9GYmcrK2Ir
            bWR2cXQrTDFpajdVUSt5Q1BSem9CNnVqRTFFClFIbU9tdGdHT3ZHSzhUck1pQlY0
            RHMxY0VUaUp6TTFsL3Q0R1VtbTFVcFUKLS0tIDhJdk5IbVg2REhLTDRYcnVkK2dh
            cndPUDlIZ1dqT0xVcjIzREhnbkRKM3MKT+u+g2PGmwwVGXkvFs5w+ZLtc5NKJGfO
            wgCHjgik27SEZXs6+r6uPtUdRDJhucClfkPzJ+JPLIuDQ+E9F4mENA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-07T03:25:53Z"
    mac: ENC[AES256_GCM,data:v4L9cp2ygegu/yKMITMJPDS06AsEhogQ6dBC9bm6H+CeOp/FUaEbkbZs6EHNZiELjVF5oqLYdrLuCTzhCrDKWZumIzWvsH1KOOOxTALVVzYA0pSrhTg3OSH38uT5wvU80spj0hgJvzeqoGmqP3Pkqjmz8dkUcS/8f3tq2YfMwmE=,iv:H6/or05nmMccgff6aT4Gij/aLY6yN6pycUQI+ZqsUXM=,tag:Ykp32t/haC0Ec5rOGkLF4A==,type:str]
    pgp:
        - created_at: "2022-11-07T03:20:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D910MxD6sogoSAQdA571I052gP62EfDz78vjvcmbpBrjtkZeHMeizopLa+SQw
            hb/+FwQ2H37HT0UzQJvT/o1kMWAOsvQohYLZC9WdAmq0Gb4JLs2KRo5pTRSmXkv9
            0l4BfOnT5btbfCmPiGlhI0g6U64zQDZxqB4UD3azDDEyJelE6eKs1MsCw6sR1YMk
            PrjST3+2zrKGMkX+yQxY3W+D6NeMfWaXILmoK0xKwYvA85lNU92ZIeZKE/Xc/TLv
            =Dup9
            -----END PGP MESSAGE-----
          fp: CDA57D7FFB3FD45FB56D179FCD40D20000800BDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
