---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  interval: 15m
  chart:
    spec:
      chart: coder
      version: 0.27.3
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: coder-db
      namespace: coder
    - name: coder-certificate
      namespace: coder
  values:
    coder:
      annotations:
        configmap.reloader.stakater.com/reload: "coder-${SECRET_DOMAIN/./-}-tls"
      env:
        - name: CODER_ACCESS_URL
          value: "https://coder.${SECRET_DOMAIN}"
        - name: CODER_PG_CONNECTION_URL
          value: postgres://coder:coder@coder-db-postgresql:5432/coder?sslmode=disable
        # This env variable controls whether or not to auto-import the
        # "kubernetes" template on first startup. This will not work unless
        # coder.serviceAccount.workspacePerms is true.
        - name: CODER_AUTO_IMPORT_TEMPLATES
          value: "kubernetes"
      tls:
        secretNames:
          - "coder-${SECRET_DOMAIN/./-}-tls"
      service:
        annotations:
          coredns.io/hostname: "https://coder.${SECRET_DOMAIN}"
          metallb.universe.tf/loadBalancerIPs: |-
            ${METALLB_CODER_ADDR}
